from pathlib import Path
import sys
root=Path(sys.argv[1]).resolve(); api=root/'scripts'/'enterprise_ai'/'api.py'; version=root/'VERSION.txt'; text=api.read_text(encoding='utf-8')
if 'FineTuningBuildRequest' not in text:
    marker='class SettingsRequest(BaseModel):'
    models="""class FineTuningBuildRequest(BaseModel):\n    pass\n\nclass FineTuningDecisionRequest(BaseModel):\n    approve: bool\n    reason: Optional[str] = None\n\nclass FineTuningExportRequest(BaseModel):\n    format: str = \"jsonl\"\n\n"""
    text=text.replace(marker,models+marker,1)
if '/api/enterprise/fine-tuning/runs' not in text:
    marker='    @router.get("/api/enterprise/audit")'
    routes="""    @router.get(\"/api/enterprise/fine-tuning/runs\")\n    def finetune_runs(limit: int = 50, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        return {\"runs\": FineTuningDatasetManager(components.db, components.cfg.root).list_runs(principal, limit)}\n\n    @router.post(\"/api/enterprise/fine-tuning/runs\")\n    def finetune_build(body: FineTuningBuildRequest, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        return FineTuningDatasetManager(components.db, components.cfg.root).build(principal)\n\n    @router.get(\"/api/enterprise/fine-tuning/runs/{run_id}\")\n    def finetune_run(run_id: str, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        return FineTuningDatasetManager(components.db, components.cfg.root).get_run(principal, run_id)\n\n    @router.post(\"/api/enterprise/fine-tuning/examples/{example_id}/decision\")\n    def finetune_decision(example_id: str, body: FineTuningDecisionRequest, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        try: return FineTuningDatasetManager(components.db, components.cfg.root).decide(principal, example_id, body.approve, body.reason)\n        except (KeyError, ValueError) as exc: raise HTTPException(status_code=400, detail=str(exc)) from exc\n\n    @router.post(\"/api/enterprise/fine-tuning/runs/{run_id}/approve-safe\")\n    def finetune_approve_safe(run_id: str, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        return FineTuningDatasetManager(components.db, components.cfg.root).approve_all_safe(principal, run_id)\n\n    @router.post(\"/api/enterprise/fine-tuning/runs/{run_id}/export\")\n    def finetune_export(run_id: str, body: FineTuningExportRequest, principal: Principal = Depends(admin_dependency)):\n        from .fine_tuning_dataset import FineTuningDatasetManager\n        try: return FineTuningDatasetManager(components.db, components.cfg.root).export(principal, run_id, body.format)\n        except (KeyError, ValueError) as exc: raise HTTPException(status_code=400, detail=str(exc)) from exc\n\n"""
    text=text.replace(marker,routes+marker,1)
api.write_text(text,encoding='utf-8'); version.write_text('8.5.5-r10.12-controlled-finetune-dataset\n',encoding='utf-8'); print('R10.12 patch OK')
