from __future__ import annotations

UNIFIED_ADMIN_HTML = r'''<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>IA Empresarial Local - Administración</title>
<style>
:root{--bg:#f4f7fb;--card:#fff;--ink:#142033;--muted:#64748b;--line:#dbe3ee;--blue:#2563eb;--green:#15803d;--red:#b91c1c;--amber:#b45309;--nav:#0f172a}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Segoe UI,Arial,sans-serif}.layout{display:grid;grid-template-columns:250px 1fr;min-height:100vh}.side{background:var(--nav);color:#fff;padding:20px 14px}.brand{font-weight:800;font-size:18px;margin:4px 8px 22px}.nav button{width:100%;border:0;background:transparent;color:#cbd5e1;text-align:left;padding:11px 12px;border-radius:9px;margin:2px 0;cursor:pointer}.nav button.active,.nav button:hover{background:#1e293b;color:#fff}.main{padding:24px;min-width:0}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.links a{margin-left:12px;color:var(--blue);text-decoration:none}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}.metric,.card{background:var(--card);border:1px solid var(--line);border-radius:14px;box-shadow:0 6px 22px #2342a30c}.metric{padding:15px}.metric b{font-size:24px;display:block;margin-top:4px}.card{padding:18px;margin:14px 0}.panel{display:none}.panel.active{display:block}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}input,select,textarea{border:1px solid #cbd5e1;border-radius:8px;padding:8px;width:100%;font:inherit}textarea{min-height:75px}.btn{border:0;border-radius:8px;padding:8px 11px;background:var(--blue);color:#fff;cursor:pointer}.btn.ok{background:var(--green)}.btn.warn{background:var(--amber)}.btn.danger{background:var(--red)}.btn.muted{background:#64748b}.table{overflow:auto}.table table{width:100%;border-collapse:collapse;font-size:13px}.table th,.table td{text-align:left;padding:9px;border-bottom:1px solid #e5e7eb;vertical-align:top}.pill{display:inline-block;padding:3px 7px;border-radius:999px;background:#e2e8f0;font-size:11px}.pill.VALIDADO{background:#dcfce7;color:#166534}.pill.PROPUESTO{background:#fef3c7;color:#92400e}.pill.RECHAZADO,.pill.OBSOLETO{background:#fee2e2;color:#991b1b}.mutedtxt{color:var(--muted);font-size:12px}.notice{background:#eff6ff;border:1px solid #bfdbfe;border-radius:10px;padding:10px;margin:12px 0}.error{background:#fef2f2;border-color:#fecaca}.formgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.actions{white-space:nowrap}.empty{padding:18px;color:var(--muted)}pre{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:12px;border-radius:10px;max-height:420px;overflow:auto}@media(max-width:950px){.layout{grid-template-columns:1fr}.side{position:sticky;top:0;z-index:5;padding:10px}.brand{margin:0 8px 8px}.nav{display:flex;overflow:auto}.nav button{width:auto;white-space:nowrap}.grid{grid-template-columns:repeat(2,1fr)}.formgrid{grid-template-columns:1fr}}
</style></head><body>
<div class="layout"><aside class="side"><div class="brand">IA Empresarial Local<br><span style="font-size:11px;font-weight:400;color:#94a3b8">R10.10 Administración Unificada</span></div><div class="nav" id="nav">
<button data-p="resumen" class="active">Resumen</button><button data-p="memoria">Memoria</button><button data-p="documentos">Documentos / RAG</button><button data-p="semantica">Diccionario</button><button data-p="reglas">Reglas empresariales</button><button data-p="analiticas">Reglas analíticas</button><button data-p="feedback">Feedback</button><button data-p="trazas">Trazabilidad</button><button data-p="historial">Historial</button><button data-p="auditoria">Auditoría</button></div></aside>
<main class="main"><div class="top"><div><h2 style="margin:0">Administración empresarial</h2><div class="mutedtxt">Conocimiento, gobernanza, aprendizaje y trazabilidad en una sola consola.</div></div><div class="links"><a id="assistant" href="/assistant">Asistente</a><a href="/">Analizador</a></div></div><div id="auth" class="notice error" style="display:none">Falta token. Abre la administración desde el acceso local autorizado.</div><div id="msg"></div>
<section id="resumen" class="panel active"><div class="grid" id="metrics"></div><div class="card"><h3>Estado de conocimiento</h3><div id="statusSummary"></div></div></section>
<section id="memoria" class="panel"><div class="card"><h3>Memoria permanente</h3><div class="formgrid"><input id="memText" placeholder="Conocimiento o preferencia"><select id="memCategory"><option>conocimiento_empresa</option><option>regla_negocio</option><option>definicion</option><option>preferencia</option><option>procedimiento</option></select></div><div style="margin-top:8px"><button class="btn" onclick="createMemory()">Guardar memoria</button></div></div><div class="card table" id="memoryTable"></div></section>
<section id="documentos" class="panel"><div class="card"><h3>Documentos / RAG</h3><input type="file" id="docFile"><div style="margin-top:8px"><button class="btn" onclick="uploadDoc()">Indexar documento</button></div></div><div class="card table" id="docsTable"></div></section>
<section id="semantica" class="panel"><div class="card"><h3>Diccionario empresarial</h3><div class="formgrid"><input id="semPhysical" placeholder="Nombre físico: Cve_Clie"><input id="semName" placeholder="Concepto: customer_id"><input id="semArea" placeholder="Área (opcional)"><input id="semDesc" placeholder="Descripción"></div><div style="margin-top:8px"><button class="btn" onclick="proposeSemantic()">Crear propuesta</button></div></div><div class="card table" id="semanticTable"></div></section>
<section id="reglas" class="panel"><div class="card"><h3>Reglas empresariales</h3><div class="formgrid"><input id="ruleName" placeholder="Nombre: UTILIDAD_REAL"><input id="ruleArea" placeholder="Área"><textarea id="ruleExpression" placeholder="Expresión: Venta - Costo - Flete"></textarea><textarea id="ruleDesc" placeholder="Descripción"></textarea></div><button class="btn" onclick="proposeRule()">Crear propuesta</button></div><div class="card table" id="rulesTable"></div></section>
<section id="analiticas" class="panel"><div class="card"><h3>Bindings analíticos</h3><div class="mutedtxt">Vincula una regla VALIDADO con una función del motor determinístico.</div><div class="formgrid"><input id="bindRule" placeholder="ID de regla VALIDADO"><select id="bindType"><option value="metric">metric</option><option value="row_filter">row_filter</option></select><input id="bindTarget" placeholder="Target: profit / sales_valid / commission"><input id="bindPriority" value="100" type="number"></div><button class="btn" onclick="bindAnalytic()">Vincular regla</button></div><div class="card table" id="analyticTable"></div></section>
<section id="feedback" class="panel"><div class="card"><h3>Feedback y propuestas</h3><div class="mutedtxt">Una corrección permanece PROPUESTO hasta validación explícita.</div></div><div class="card table" id="feedbackTable"></div></section>
<section id="trazas" class="panel"><div class="card"><h3>Trazabilidad</h3><div id="traceExplain"></div></div><div class="card table" id="traceTable"></div></section>
<section id="historial" class="panel"><div class="card"><h3>Historial / versiones</h3><div class="formgrid"><select id="histType"><option value="business_rule">business_rule</option><option value="semantic_definition">semantic_definition</option></select><input id="histId" placeholder="ID del objeto"></div><button class="btn" onclick="loadHistory()">Consultar historial</button><div id="historyOut"></div></div></section>
<section id="auditoria" class="panel"><div class="card"><h3>Auditoría</h3><div class="table" id="auditTable"></div></div></section>
</main></div>
<script>
const hp=new URLSearchParams(location.hash.replace(/^#/,'')),ht=hp.get('token')||'';if(ht){localStorage.setItem('iaToken',ht);history.replaceState(null,'',location.pathname)}const token=ht||localStorage.getItem('iaToken')||'';if(!token)document.getElementById('auth').style.display='block';document.getElementById('assistant').href='/assistant#token='+encodeURIComponent(token);
const H=()=>({'Authorization':'Bearer '+token});const J=()=>({'Authorization':'Bearer '+token,'Content-Type':'application/json'});const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(t,err=false){document.getElementById('msg').innerHTML='<div class="notice '+(err?'error':'')+'>'+esc(t)+'</div>';setTimeout(()=>document.getElementById('msg').innerHTML='',4500)}
async function api(url,opt={}){const r=await fetch(url,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||d.error||('HTTP '+r.status));return d}
function pill(s){return '<span class="pill '+esc(s)+'">'+esc(s||'N/D')+'</span>'}function table(rows,cols,actions){if(!rows||!rows.length)return '<div class="empty">Sin registros.</div>';return '<table><thead><tr>'+cols.map(c=>'<th>'+esc(c[0])+'</th>').join('')+(actions?'<th>Acciones</th>':'')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+cols.map(c=>'<td>'+(c[2]?c[2](r[c[1]],r):esc(r[c[1]]??''))+'</td>').join('')+(actions?'<td class="actions">'+actions(r)+'</td>':'')+'</tr>').join('')+'</tbody></table>'}
async function refreshAll(){if(!token)return;try{const [ov,m,d,s,r,a,f,t]=await Promise.all([api('/api/enterprise/admin/overview',{headers:H()}),api('/api/enterprise/memories?include_inactive=true',{headers:H()}),api('/api/enterprise/documents',{headers:H()}),api('/api/enterprise/semantic-definitions?include_inactive=true',{headers:H()}),api('/api/enterprise/business-rules?include_inactive=true',{headers:H()}),api('/api/enterprise/analytic-rules',{headers:H()}),api('/api/enterprise/feedback',{headers:H()}),api('/api/enterprise/traces?limit=100',{headers:H()})]);renderOverview(ov);renderMem(m.memories);renderDocs(d.documents);renderSem(s.items);renderRules(r.items);renderAnalytic(a.items);renderFeedback(f.feedback||f.items);renderTraces(t.traces);loadAudit()}catch(e){toast(e.message,true)}}
function renderOverview(o){const c=o.counts||{};document.getElementById('metrics').innerHTML=[['Memorias',c.memories],['Documentos',c.documents],['Reglas',c.rules],['Definiciones',c.semantic_definitions],['Feedback pendiente',c.feedback_pending],['Trazas',c.traces],['Datasets',c.datasets],['Conflictos',c.conflicts]].map(x=>'<div class="metric"><span class="mutedtxt">'+esc(x[0])+'</span><b>'+esc(x[1]??0)+'</b></div>').join('');document.getElementById('statusSummary').innerHTML=table(o.statuses||[],[['Tipo','type'],['Estado','status',(v)=>pill(v)],['Cantidad','count']])}
function renderMem(rows){document.getElementById('memoryTable').innerHTML=table(rows,[['Categoría','category'],['Contenido','content'],['Confianza','confidence'],['Confirmada','confirmed',(v)=>v?'Sí':'No'],['Activa','active',(v)=>v?'Sí':'No']],r=>'<button class="btn ok" onclick="confirmMem(\''+r.id+'\')">Confirmar</button> <button class="btn danger" onclick="deleteMem(\''+r.id+'\')">Desactivar</button>')}
function renderDocs(rows){document.getElementById('docsTable').innerHTML=table(rows,[['Documento','name'],['Versión','current_version'],['Chunks','chunk_count'],['Estado','active',(v)=>v?'Activo':'Inactivo']],r=>'<button class="btn" onclick="reindexDoc(\''+r.id+'\')">Reindexar</button> <button class="btn danger" onclick="deleteDoc(\''+r.id+'\')">Eliminar</button>')}
function renderSem(rows){document.getElementById('semanticTable').innerHTML=table(rows,[['Físico','physical_name'],['Semántico','semantic_name'],['Área','area'],['Estado','status',(v)=>pill(v)],['Versión','version'],['Vigencia','valid_from',(v,r)=>esc((v||'∞')+' → '+(r.valid_to||'∞'))]],r=>r.status==='PROPUESTO'?'<button class="btn ok" onclick="validateSem(\''+r.id+'\')">Validar</button> <button class="btn danger" onclick="rejectSem(\''+r.id+'\')">Rechazar</button>':'')}
function renderRules(rows){document.getElementById('rulesTable').innerHTML=table(rows,[['Nombre','name'],['Área','area'],['Expresión','expression'],['Estado','status',(v)=>pill(v)],['Versión','version'],['Vigencia','valid_from',(v,r)=>esc((v||'∞')+' → '+(r.valid_to||'∞'))]],r=>r.status==='PROPUESTO'?'<button class="btn ok" onclick="validateRule(\''+r.id+'\')">Validar</button> <button class="btn danger" onclick="rejectRule(\''+r.id+'\')">Rechazar</button>':(r.status==='VALIDADO'?'<button class="btn warn" onclick="obsoleteRule(\''+r.id+'\')">Obsoletar</button>':''))}
function renderAnalytic(rows){document.getElementById('analyticTable').innerHTML=table(rows,[['Regla','rule_name'],['Tipo','rule_type'],['Target','target'],['Prioridad','priority'],['Estado regla','rule_status',(v)=>pill(v)]])}
function renderFeedback(rows){document.getElementById('feedbackTable').innerHTML=table(rows,[['Tipo','feedback_type'],['Corrección','correction'],['Propuesta','proposal_type'],['Estado','proposal_status',(v)=>pill(v)],['Fecha','created_at']],r=>r.proposal_status==='PROPUESTO'?'<button class="btn ok" onclick="validateFeedback(\''+r.id+'\')">Validar</button> <button class="btn danger" onclick="rejectFeedback(\''+r.id+'\')">Rechazar</button>':'')}
function renderTraces(rows){document.getElementById('traceTable').innerHTML=table(rows,[['Tipo','trace_type'],['Prompt','prompt_preview'],['Estado','status'],['Fecha','created_at']],r=>'<button class="btn" onclick="explainTrace(\''+r.id+'\')">Explicar</button>')}
async function createMemory(){try{await api('/api/enterprise/memories',{method:'POST',headers:J(),body:JSON.stringify({content:memText.value,category:memCategory.value,scope:'company'})});toast('Memoria creada');refreshAll()}catch(e){toast(e.message,true)}}
async function confirmMem(id){try{await api('/api/enterprise/memories/'+id+'/confirm',{method:'POST',headers:H()});refreshAll()}catch(e){toast(e.message,true)}}async function deleteMem(id){try{await api('/api/enterprise/memories/'+id,{method:'DELETE',headers:H()});refreshAll()}catch(e){toast(e.message,true)}}
async function uploadDoc(){try{const f=docFile.files[0];if(!f)throw new Error('Selecciona un archivo');const fd=new FormData();fd.append('file',f);fd.append('scope','company');await api('/api/enterprise/documents',{method:'POST',headers:H(),body:fd});toast('Documento indexado');refreshAll()}catch(e){toast(e.message,true)}}async function reindexDoc(id){try{await api('/api/enterprise/documents/'+id+'/reindex',{method:'POST',headers:H()});refreshAll()}catch(e){toast(e.message,true)}}async function deleteDoc(id){try{await api('/api/enterprise/documents/'+id,{method:'DELETE',headers:H()});refreshAll()}catch(e){toast(e.message,true)}}
async function proposeSemantic(){try{await api('/api/enterprise/semantic-definitions',{method:'POST',headers:J(),body:JSON.stringify({physical_name:semPhysical.value,semantic_name:semName.value,area:semArea.value||null,description:semDesc.value||null})});refreshAll()}catch(e){toast(e.message,true)}}async function validateSem(id){try{await api('/api/enterprise/semantic-definitions/'+id+'/validate',{method:'POST',headers:J(),body:'{}'});refreshAll()}catch(e){if(confirm(e.message+'\n¿Deseas reemplazar conflictos validados?')){await api('/api/enterprise/semantic-definitions/'+id+'/validate',{method:'POST',headers:J(),body:JSON.stringify({replace_conflicts:true})});refreshAll()}}}async function rejectSem(id){await api('/api/enterprise/semantic-definitions/'+id+'/reject',{method:'POST',headers:H()});refreshAll()}
async function proposeRule(){try{await api('/api/enterprise/business-rules',{method:'POST',headers:J(),body:JSON.stringify({name:ruleName.value,area:ruleArea.value||null,expression:ruleExpression.value,description:ruleDesc.value||null})});refreshAll()}catch(e){toast(e.message,true)}}async function validateRule(id){try{await api('/api/enterprise/business-rules/'+id+'/validate',{method:'POST',headers:J(),body:'{}'});refreshAll()}catch(e){if(confirm(e.message+'\n¿Deseas reemplazar conflictos validados?')){await api('/api/enterprise/business-rules/'+id+'/validate',{method:'POST',headers:J(),body:JSON.stringify({replace_conflicts:true})});refreshAll()}}}async function rejectRule(id){await api('/api/enterprise/business-rules/'+id+'/reject',{method:'POST',headers:H()});refreshAll()}async function obsoleteRule(id){await api('/api/enterprise/business-rules/'+id+'/obsolete',{method:'POST',headers:H()});refreshAll()}
async function bindAnalytic(){try{await api('/api/enterprise/rules/'+bindRule.value+'/bind',{method:'POST',headers:J(),body:JSON.stringify({rule_type:bindType.value,target:bindTarget.value,priority:Number(bindPriority.value||100),scope:'company'})});refreshAll()}catch(e){toast(e.message,true)}}
async function validateFeedback(id){try{await api('/api/enterprise/feedback/'+id+'/validate',{method:'POST',headers:J(),body:'{}'});refreshAll()}catch(e){toast(e.message,true)}}async function rejectFeedback(id){await api('/api/enterprise/feedback/'+id+'/reject',{method:'POST',headers:H()});refreshAll()}
async function explainTrace(id){try{const d=await api('/api/enterprise/traces/'+id+'/explain',{headers:H()});document.getElementById('traceExplain').innerHTML='<pre>'+esc(d.explanation||JSON.stringify(d,null,2))+'</pre>'}catch(e){toast(e.message,true)}}
async function loadHistory(){try{const d=await api('/api/enterprise/knowledge/'+encodeURIComponent(histType.value)+'/'+encodeURIComponent(histId.value)+'/history',{headers:H()});historyOut.innerHTML='<pre>'+esc(JSON.stringify(d,null,2))+'</pre>'}catch(e){toast(e.message,true)}}
async function loadAudit(){try{const d=await api('/api/enterprise/audit?limit=100',{headers:H()});document.getElementById('auditTable').innerHTML=table(d.events,[['Evento','event_type'],['Objeto','object_type'],['Resultado','outcome'],['Fecha','created_at']])}catch(e){document.getElementById('auditTable').innerHTML='<div class="empty">Auditoría disponible solo para administrador.</div>'}}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.p).classList.add('active')});refreshAll();
</script></body></html>'''
