from __future__ import annotations

CSS = """
:root{--n:#071a36;--b:#1d67d2;--bg:#f5f7fb;--t:#152238;--m:#657289;--l:#e1e7ef;--surface:#fff;--ok:#14804a;--w:#9a6200;--bad:#b42318}:root[data-theme="professional-dark"]{--n:#0b1d39;--bg:#101827;--t:#e8eef8;--m:#b5c1d5;--l:#30425d;--surface:#172235}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,Segoe UI,Arial,sans-serif;background:var(--bg);color:var(--t)}button,input,textarea{font:inherit}.hidden{display:none!important}
.shell{min-height:100vh;display:grid;grid-template-columns:248px minmax(0,1fr)}.side{height:100vh;position:sticky;top:0;background:linear-gradient(180deg,var(--n),#06152d);color:#fff;padding:24px 18px;display:flex;flex-direction:column}.mark{width:42px;height:42px;border-radius:13px;background:#fff;color:var(--n);display:grid;place-items:center;font-weight:900;margin:0 9px 13px}.company{padding:0 9px;font-weight:800}.product{padding:4px 9px 20px;color:#a9bdd8;font-size:12px}.nav{display:flex;flex-direction:column;gap:5px}.nav a{text-decoration:none;color:#c6d5e8;padding:11px 12px;border-radius:11px;font-size:14px;font-weight:650;min-height:44px;display:flex;align-items:center}.nav a.active{background:#fff;color:var(--n)}.privacy{margin-top:auto;border:1px solid #ffffff20;border-radius:13px;padding:12px;color:#b9c9df;font-size:11px;line-height:1.5}
.main{min-width:0}.top{height:72px;background:var(--surface);border-bottom:1px solid var(--l);display:flex;align-items:center;justify-content:space-between;padding:0 30px}.user{display:flex;align-items:center;gap:10px}.who{text-align:right}.name{font-size:13px;font-weight:750}.role{font-size:11px;color:var(--m)}.avatar{width:36px;height:36px;border-radius:50%;background:var(--n);color:#fff;display:grid;place-items:center;font-weight:800}.content{padding:31px;max-width:1450px;margin:auto}.eyebrow{font-size:12px;color:var(--b);font-weight:850;text-transform:uppercase;letter-spacing:.08em}h1{font-size:30px;margin:8px 0}.lead{color:var(--m);font-size:15px;line-height:1.6;max-width:800px;margin:0 0 24px}
.grid{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:18px}.card{background:var(--surface);border:1px solid var(--l);border-radius:18px;box-shadow:0 14px 38px #0f23410d;padding:22px}.s12{grid-column:span 12}.s7{grid-column:span 7}.s5{grid-column:span 5}.card h2{font-size:17px;margin:0 0 6px}.copy{font-size:13px;color:var(--m);line-height:1.55;margin:0}
.field{margin:17px 0}label{display:block;font-size:12px;font-weight:750;margin-bottom:7px}input[type=file],input[type=text],input[type=password],input[type=color],select,textarea{width:100%;border:1px solid #cad4e1;border-radius:12px;padding:12px;background:var(--surface);color:var(--t)}input[type=color]{height:46px;padding:4px}select{min-height:46px}input[type=file]{font-size:12px;padding:8px}textarea{min-height:130px;resize:vertical;line-height:1.5}.actions{display:flex;flex-wrap:wrap;gap:9px;align-items:center}.actions a{text-decoration:none}.btn{border:0;border-radius:11px;min-height:44px;padding:10px 14px;font-size:13px;font-weight:750;background:var(--n);color:#fff;cursor:pointer}.btn.primary{background:var(--b)}.btn.secondary,.logout{background:var(--surface);color:var(--t);border:1px solid var(--l)}.btn:disabled{opacity:.5}
.status{margin-top:13px;border-radius:12px;padding:11px 13px;font-size:12px}.info{background:#edf5ff;color:#285887}.success{background:#eaf8f0;color:var(--ok)}.warning{background:#fff7e6;color:var(--w)}.error{background:#fff0ee;color:var(--bad)}.section-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:15px}.list{display:flex;flex-direction:column;gap:10px}.item{border:1px solid var(--l);border-radius:14px;padding:14px;display:flex;justify-content:space-between;gap:12px;align-items:center}.item-title{font-size:13px;font-weight:780}.item-meta{font-size:11px;color:var(--m);margin-top:4px}.badge{border-radius:999px;padding:5px 9px;font-size:10px;font-weight:800;background:#eaf8f0;color:var(--ok);white-space:nowrap}.empty{border:1px dashed #cbd5e1;border-radius:14px;padding:24px;text-align:center;color:var(--m);font-size:12px}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric{border:1px solid var(--l);border-radius:14px;padding:15px}.metric-value{font-size:26px;font-weight:850}.metric-label{font-size:11px;color:var(--m);margin-top:5px}.quick-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.quick{border:1px solid #cfe0f8;background:#f6faff;color:#285887;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:700;cursor:pointer}
.login{min-height:100vh;background:linear-gradient(145deg,#06152d,#0d2850);display:grid;place-items:center;padding:22px}.login-card{width:min(430px,100%);background:#fff;border-radius:22px;padding:32px;box-shadow:0 28px 80px #00000047}.login-copy{font-size:13px;color:var(--m);margin-bottom:20px}.login-error{font-size:12px;color:var(--bad);min-height:18px;margin-top:10px}.mobile{display:none}
@media(max-width:1080px){.s7,.s5{grid-column:span 12}}@media(max-width:820px){.shell{display:block}.side{display:none}.top{height:auto;min-height:64px;padding:12px 16px}.content{padding:22px 16px 102px}.who{display:none}.mobile{position:fixed;z-index:20;left:10px;right:10px;bottom:10px;background:var(--n);padding:5px;border-radius:17px;display:flex;justify-content:space-around;gap:2px}.mobile a{text-decoration:none;color:#bed0e7;font-size:11px;text-align:center;min-width:44px;min-height:44px;padding:6px 5px;border-radius:9px;display:flex;align-items:center;justify-content:center}.mobile a.active{background:#fff;color:var(--n)}}@media(max-width:560px){h1{font-size:25px}.metrics{grid-template-columns:1fr}.item{align-items:flex-start;flex-direction:column}.card{padding:17px}}
"""

COMMON_JS = """
let token=sessionStorage.getItem('iaEnterpriseSession')||'',APP=null;const q=id=>document.getElementById(id),txt=v=>String(v??'');
function initials(v){const p=txt(v).trim().split(/\\s+/).filter(Boolean);return(p.slice(0,2).map(x=>x[0]).join('')||'IA').toUpperCase()}
function status(id,msg,kind='info'){const e=q(id);if(!e)return;e.className='status '+kind+(msg?'':' hidden');e.textContent=txt(msg)}
async function pf(url,opt={}){const h={...(opt.headers||{}),Authorization:'Bearer '+token};const r=await fetch(url,{...opt,headers:h});if(r.status===401){showLogin('Tu sesión terminó. Inicia sesión nuevamente.');return null}return r}
function showLogin(msg=''){token='';APP=null;sessionStorage.removeItem('iaEnterpriseSession');q('shell').classList.add('hidden');q('login').classList.remove('hidden');q('loginError').textContent=msg}
function applyContext(p){APP=p||{};const c=APP.company||{},u=APP.user||{},cn=txt(c.display_name||'Mi empresa'),un=txt(u.display_name||u.username||'Usuario'),accent=txt(c.accent_color||'');document.documentElement.dataset.theme=c.theme==='professional-dark'?'professional-dark':'professional-light';if(/^#[0-9a-f]{6}$/i.test(accent))document.documentElement.style.setProperty('--b',accent);else document.documentElement.style.removeProperty('--b');q('brandCompany').textContent=cn;q('topCompany').textContent=cn;q('userName').textContent=un;q('userRole').textContent=txt(u.role_label||'Usuario');q('avatar').textContent=initials(un);for(const a of document.querySelectorAll('[data-settings]'))a.classList.toggle('hidden',!Boolean((APP.capabilities||{}).settings))}
async function establish(load){if(!token){showLogin();return false}try{const r=await pf('/api/enterprise/app-context');if(!r||!r.ok)throw new Error();applyContext(await r.json());q('login').classList.add('hidden');q('shell').classList.remove('hidden');if(load)await load();return true}catch(_){showLogin('No se pudo validar la sesión con el servicio local.');return false}}
async function login(load){const b=q('loginButton'),p=q('loginPassword');b.disabled=true;q('loginError').textContent='';try{const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:q('loginUser').value.trim(),password:p.value})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.token){q('loginError').textContent='Usuario o contraseña incorrectos.';return}token=d.token;sessionStorage.setItem('iaEnterpriseSession',token);p.value='';await establish(load)}catch(_){q('loginError').textContent='No se pudo conectar con el servicio local.'}finally{b.disabled=false}}
async function logout(){try{if(token)await pf('/api/auth/logout',{method:'POST'})}catch(_){}showLogin('Sesión cerrada.')}
function bind(load){q('loginButton').onclick=()=>login(load);q('loginPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login(load)});q('logoutButton').onclick=logout;establish(load)}
"""

def navigation(active):
    items=[("app","/app","Inicio"),("assistant","/assistant","Asistente"),("analyze","/analyze","Analizar"),("data","/data","Datos"),("reports","/reports","Reportes")]
    desktop=[]; mobile=[]
    for key,url,label in items:
        cls="active" if key==active else ""
        desktop.append(f'<a class="{cls}" href="{url}">{label}</a>')
        mobile.append(f'<a class="{cls}" href="{url}">{label}</a>')
    settings_class="active" if active=="settings" else ""
    desktop.append(f'<a data-settings class="{settings_class} hidden" href="/settings">Configuración</a>')
    mobile.append(f'<a data-settings class="{settings_class} hidden" href="/settings">Configuración</a>')
    return "".join(desktop),"".join(mobile)

def page(title,active,heading,lead,body,script):
    nav,mobile=navigation(active)
    return f"""<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title} · IA Empresarial Local</title><style>{CSS}</style></head><body>
<section id="login" class="login"><div class="login-card"><div class="mark" style="margin:0 0 18px;background:#071a36;color:#fff">IA</div><h2>Bienvenido</h2><div class="login-copy">Accede a la información y herramientas de tu empresa.</div><div class="field"><label>Usuario</label><input id="loginUser" type="text" autocomplete="username"></div><div class="field"><label>Contraseña</label><input id="loginPassword" type="password" autocomplete="current-password"></div><button id="loginButton" class="btn primary" style="width:100%">Entrar</button><div id="loginError" class="login-error"></div></div></section>
<div id="shell" class="shell hidden"><aside class="side"><div class="mark">IA</div><div id="brandCompany" class="company">Mi empresa</div><div class="product">IA Empresarial Local</div><nav class="nav">{nav}</nav><div class="privacy">La información se procesa dentro de la plataforma empresarial configurada para tu organización.</div></aside><main class="main"><header class="top"><div id="topCompany">Mi empresa</div><div class="user"><div class="who"><div id="userName" class="name">Usuario</div><div id="userRole" class="role">Usuario</div></div><div id="avatar" class="avatar">IA</div><button id="logoutButton" class="btn logout">Salir</button></div></header><div class="content"><div class="eyebrow">{title}</div><h1>{heading}</h1><p class="lead">{lead}</p>{body}</div></main><nav class="mobile">{mobile}</nav></div><script>{COMMON_JS}{script}</script></body></html>"""

ANALYZE_BODY = """
<div class="grid"><section class="card s7"><h2>Nuevo análisis</h2><p class="copy">Selecciona un archivo y explica con tus palabras qué resultado necesitas.</p><div class="field"><label>Archivo</label><input id="analysisFile" type="file" accept=".xlsx,.xls,.xlsb,.xlsm,.csv,.txt"></div><div class="field"><label>¿Qué quieres analizar?</label><textarea id="analysisPrompt" placeholder="Ejemplo: ventas totales, evolución mensual, principales clientes, productos en caída y resumen ejecutivo."></textarea><div class="quick-row"><button class="quick" data-prompt="Genera un resumen ejecutivo con los indicadores más importantes, tendencias y puntos que requieren atención.">Resumen ejecutivo</button><button class="quick" data-prompt="Analiza la evolución mensual e identifica crecimiento o caída.">Evolución</button><button class="quick" data-prompt="Identifica principales clientes, productos y oportunidades.">Principales resultados</button></div></div><div class="actions"><button id="runAnalysis" class="btn primary">Analizar archivo</button><a class="btn secondary" href="/reports">Ver reportes</a></div><div id="analysisStatus" class="status info hidden"></div></section>
<aside class="card s5"><h2>Qué obtendrás</h2><p class="copy">Resultados empresariales listos para consultar o compartir.</p><div class="list" style="margin-top:16px"><div class="item"><div><div class="item-title">Indicadores y hallazgos</div><div class="item-meta">Totales, tendencias, comparativos y señales relevantes.</div></div><span class="badge">Incluido</span></div><div class="item"><div><div class="item-title">Panel visual</div><div class="item-meta">Una vista interactiva cuando el análisis lo requiere.</div></div><span class="badge">Incluido</span></div><div class="item"><div><div class="item-title">Archivos de salida</div><div class="item-meta">Los formatos generados quedan disponibles en Reportes.</div></div><span class="badge">Incluido</span></div></div></aside>
<section id="analysisResultCard" class="card s12 hidden"><div class="section-head"><div><h2>Resultado</h2><p class="copy">El análisis terminó correctamente.</p></div><span class="badge">Listo</span></div><div id="analysisResult"></div><div id="analysisActions" class="actions" style="margin-top:15px"></div></section></div>
"""

ANALYZE_JS = """
function mkAction(label,fn){const b=document.createElement('button');b.className='btn secondary';b.textContent=label;b.onclick=fn;return b}
async function runAnalysis(){const file=q('analysisFile').files[0],prompt=q('analysisPrompt').value.trim(),button=q('runAnalysis');if(!file){status('analysisStatus','Selecciona un archivo para comenzar.','warning');return}if(!prompt){status('analysisStatus','Escribe qué quieres conocer o generar con esa información.','warning');return}button.disabled=true;q('analysisResultCard').classList.add('hidden');status('analysisStatus','Analizando la información. Esto puede tardar unos momentos...','info');try{const form=new FormData();form.append('file',file);form.append('prompt',prompt);if(window.crypto&&crypto.randomUUID)form.append('request_id',crypto.randomUUID());const r=await pf('/api/analyze',{method:'POST',body:form});if(!r)return;const d=await r.json().catch(()=>({}));if(!r.ok){const x=d.detail;status('analysisStatus',typeof x==='string'?x:(x&&x.message)||'No se pudo completar el análisis.','error');return}status('analysisStatus','Análisis completado correctamente.','success');const result=q('analysisResult');result.replaceChildren();const t=document.createElement('div'),m=document.createElement('div');t.className='item-title';m.className='item-meta';t.textContent='Resultado empresarial generado';const p=[];if(Number.isFinite(Number(d.filas)))p.push(Number(d.filas).toLocaleString()+' filas procesadas');if(d.segundos!==undefined)p.push(txt(d.segundos)+' s');m.textContent=p.join(' · ')||'Resultado disponible';result.append(t,m);if(txt(d.narrativa).trim()){const summary=document.createElement('div');summary.className='item-meta';summary.style.marginTop='12px';summary.textContent=txt(d.narrativa);result.append(summary)}const a=q('analysisActions');a.replaceChildren();const dashboard=d.dashboard||d.html;if(dashboard)a.appendChild(mkAction('Abrir panel',()=>window.open('/dashboard/'+encodeURIComponent(dashboard),'_blank','noopener')));if(d.pdf)a.appendChild(mkAction('Descargar PDF',()=>window.open('/download/'+encodeURIComponent(d.pdf),'_blank')));if(d.excel)a.appendChild(mkAction('Descargar Excel',()=>window.open('/download/'+encodeURIComponent(d.excel),'_blank')));const link=document.createElement('a');link.className='btn secondary';link.href='/reports';link.textContent='Ver todos los reportes';a.appendChild(link);q('analysisResultCard').classList.remove('hidden')}catch(_){status('analysisStatus','No se pudo completar el análisis local.','error')}finally{button.disabled=false}}
for(const b of document.querySelectorAll('[data-prompt]'))b.onclick=()=>{q('analysisPrompt').value=b.dataset.prompt||'';q('analysisPrompt').focus()};q('runAnalysis').onclick=runAnalysis;bind(async()=>{});
"""

DATA_BODY = """
<div class="grid"><section class="card s12"><div class="metrics"><div class="metric"><div id="documentCount" class="metric-value">—</div><div class="metric-label">Archivos disponibles</div></div><div class="metric"><div id="datasetCount" class="metric-value">—</div><div class="metric-label">Conjuntos listos para análisis</div></div><div class="metric"><div id="connectionCount" class="metric-value">—</div><div class="metric-label">Conexiones empresariales</div></div></div></section>
<section class="card s7"><div class="section-head"><div><h2>Información disponible</h2><p class="copy">Archivos y conjuntos que la plataforma puede utilizar para responder preguntas y generar análisis.</p></div><button id="refreshData" class="btn secondary">Actualizar</button></div><div id="dataStatus" class="status info hidden"></div><h2 style="margin-top:20px">Archivos</h2><div id="documentList" class="list"></div><h2 style="margin-top:24px">Datos listos para análisis</h2><div id="datasetList" class="list"></div></section>
<aside class="card s5"><h2>Agregar información</h2><p class="copy">Sube un archivo para que quede disponible dentro del entorno empresarial.</p><div class="field"><label>Seleccionar archivo</label><input id="dataFile" type="file" accept=".csv,.xlsx,.xls,.xlsm,.xlsb,.pdf,.docx,.txt,.md,.markdown"></div><button id="uploadData" class="btn primary">Agregar información</button><div id="uploadStatus" class="status info hidden"></div><div style="height:1px;background:var(--l);margin:24px 0"></div><h2>Conexiones empresariales</h2><p class="copy">Fuentes administradas y autorizadas para tu organización.</p><div id="connectionList" class="list" style="margin-top:15px"></div><div class="actions" style="margin-top:16px"><a data-settings class="btn secondary hidden" href="/settings">Configurar fuentes</a><a class="btn secondary" href="/analyze">Crear análisis</a></div></aside></div>
"""

DATA_JS = """
function emptyBox(el,msg){el.replaceChildren();const x=document.createElement('div');x.className='empty';x.textContent=msg;el.appendChild(x)}
function row(title,meta,badge='Disponible'){const x=document.createElement('div'),m=document.createElement('div'),t=document.createElement('div'),d=document.createElement('div'),b=document.createElement('span');x.className='item';t.className='item-title';d.className='item-meta';b.className='badge';t.textContent=title;d.textContent=meta;b.textContent=badge;m.append(t,d);x.append(m,b);return x}
async function loadData(){status('dataStatus','Actualizando información...','info');try{const [dr,sr,cr]=await Promise.all([pf('/api/enterprise/documents'),pf('/api/enterprise/datasets'),pf('/api/enterprise/control-plane/sql-sources')]);if(!dr||!sr)return;const docs=dr.ok?(await dr.json()).documents||[]:[],sets=sr.ok?(await sr.json()).datasets||[]:[];let con=[];if(cr&&cr.ok)con=(await cr.json()).sources||[];q('documentCount').textContent=docs.length;q('datasetCount').textContent=sets.length;q('connectionCount').textContent=con.filter(x=>x&&x.enabled!==false).length;const dl=q('documentList');dl.replaceChildren();for(const x of docs)dl.appendChild(row(x.name||'Archivo',((x.extension||'archivo').replace('.','').toUpperCase())+(x.chunk_count!==undefined?' · '+x.chunk_count+' secciones':'')));if(!docs.length)emptyBox(dl,'Todavía no hay archivos disponibles.');const sl=q('datasetList');sl.replaceChildren();for(const x of sets)sl.appendChild(row(x.name||'Datos empresariales',Array.isArray(x.columns)&&x.columns.length?x.columns.length+' campos disponibles':'Disponible para análisis','Listo'));if(!sets.length)emptyBox(sl,'Todavía no hay datos estructurados registrados.');const cl=q('connectionList');cl.replaceChildren();for(const x of con.filter(y=>y&&y.enabled!==false))cl.appendChild(row(x.display_name||x.database||'Fuente empresarial',x.database&&x.display_name?x.database:'Disponible para consulta'));if(!con.length)emptyBox(cl,'No hay conexiones empresariales disponibles todavía.');status('dataStatus','Información actualizada.','success')}catch(_){status('dataStatus','No se pudo actualizar toda la información disponible.','error')}}
async function uploadData(){const file=q('dataFile').files[0],button=q('uploadData');if(!file){status('uploadStatus','Selecciona un archivo para agregar.','warning');return}button.disabled=true;status('uploadStatus','Agregando información...','info');try{const form=new FormData();form.append('file',file);form.append('scope','company');const r=await pf('/api/enterprise/documents',{method:'POST',body:form});if(!r)return;if(!r.ok){status('uploadStatus','No se pudo agregar ese archivo. Verifica el formato y vuelve a intentar.','error');return}q('dataFile').value='';status('uploadStatus','Información agregada correctamente.','success');await loadData()}catch(_){status('uploadStatus','No se pudo agregar la información.','error')}finally{button.disabled=false}}
q('refreshData').onclick=loadData;q('uploadData').onclick=uploadData;bind(loadData);
"""

REPORTS_BODY = """
<div class="grid"><section class="card s12"><div class="section-head"><div><h2>Resultados generados</h2><p class="copy">Consulta y descarga los análisis creados para tu empresa desde un solo lugar.</p></div><div class="actions"><a class="btn primary" href="/analyze">Nuevo análisis</a><button id="refreshReports" class="btn secondary">Actualizar</button></div></div><div id="reportsStatus" class="status info hidden"></div><div id="reportList" class="list" style="margin-top:15px"></div></section></div>
"""

REPORTS_JS = """
function fmtLabel(f){f=txt(f).toLowerCase();if(f==='html')return'Abrir panel';if(f==='pdf')return'Descargar PDF';if(f==='xlsx'||f==='excel')return'Descargar Excel';if(f==='csv')return'Descargar CSV';return'Descargar '+f.toUpperCase()}
function reportsEmpty(msg){const box=q('reportList');box.replaceChildren();const x=document.createElement('div');x.className='empty';x.textContent=msg;box.appendChild(x)}
async function artifact(run,format,filename,button){button.disabled=true;status('reportsStatus','Preparando resultado...','info');try{const r=await pf('/api/deliverables/'+encodeURIComponent(run)+'/download/'+encodeURIComponent(format));if(!r)return;if(!r.ok){status('reportsStatus','Ese resultado ya no está disponible.','error');return}const blob=await r.blob(),url=URL.createObjectURL(blob);if(format==='html'){window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),60000)}else{const a=document.createElement('a');a.href=url;a.download=txt(filename||run+'.'+format).replace(/[^A-Za-z0-9._-]/g,'_');document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0)}status('reportsStatus','Resultado disponible.','success')}catch(_){status('reportsStatus','No se pudo abrir o descargar el resultado.','error')}finally{button.disabled=false}}
function renderReports(items){const box=q('reportList');box.replaceChildren();if(!items.length){reportsEmpty('Aún no hay reportes. Crea tu primer análisis para ver aquí los resultados.');return}for(const r of items){const x=document.createElement('div'),m=document.createElement('div'),t=document.createElement('div'),d=document.createElement('div'),a=document.createElement('div');x.className='item';t.className='item-title';d.className='item-meta';a.className='actions';t.textContent='Resultado empresarial';const date=r.created_at?new Date(r.created_at):null;d.textContent=date&&!Number.isNaN(date.getTime())?date.toLocaleString():'Resultado disponible';m.append(t,d);for(const f of(Array.isArray(r.deliverables)?r.deliverables:[])){if(!f||!f.format)continue;const b=document.createElement('button');b.className='btn secondary';b.textContent=fmtLabel(f.format);b.onclick=()=>artifact(r.run_id,txt(f.format).toLowerCase(),f.filename,b);a.appendChild(b)}x.append(m,a);box.appendChild(x)}}
async function loadReports(){status('reportsStatus','Actualizando resultados...','info');try{const r=await pf('/api/deliverables');if(!r)return;if(r.status===403){reportsEmpty('Tu perfil no tiene acceso a los reportes.');status('reportsStatus','Acceso restringido.','warning');return}if(!r.ok)throw new Error();const d=await r.json(),items=Array.isArray(d.items)?d.items:[];renderReports(items);status('reportsStatus',items.length?items.length+' resultado'+(items.length===1?' disponible.':'s disponibles.'):'Aún no hay resultados generados.',items.length?'success':'info')}catch(_){status('reportsStatus','No se pudieron consultar los reportes.','error')}}
q('refreshReports').onclick=loadReports;bind(loadReports);
"""

PRODUCT_ANALYZE_HTML=page("Analizar","analyze","Convierte tus datos en decisiones","Carga información de tu empresa, describe lo que necesitas y recibe un análisis listo para consultar o compartir.",ANALYZE_BODY,ANALYZE_JS)
PRODUCT_DATA_HTML=page("Datos","data","La información de tu empresa, en un solo lugar","Consulta qué información está disponible para el asistente y para tus análisis, sin preocuparte por detalles técnicos.",DATA_BODY,DATA_JS)
PRODUCT_REPORTS_HTML=page("Reportes","reports","Tus resultados, organizados y disponibles","Encuentra los análisis generados, abre tus paneles y descarga los formatos disponibles cuando los necesites.",REPORTS_BODY,REPORTS_JS)
